name: Build and Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create plugin ZIP
        run: zip -r digitizer-site-worker.zip digitizer-site-worker/

      - name: Upload ZIP to release
        uses: softprops/action-gh-release@v2
        with:
          files: digitizer-site-worker.zip
